### ISSUE TITLE
Finalize design for "List" layout

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozmaker-templates#3]
We've started the List layout, but during the March 11 heartbeat, we need to finalize. This should include:
- [x] design for specific use case (Clubs resources page) (p1)
- [x] generic design (p2)
- [x] design review and necessary revisions

**Comment by hannahkane** [comment]
@vazquez @flukeout - and this one?

**Comment by vazquez** [comment]
We have the template up on the `mozmaker-templates` repo, and it has undergone 2 design reviews. This is good to close, any additional work to be filed as separate tickets.
