### ISSUE TITLE
Determine strategy for images in templates

### ISSUE THREAD

**Issue by gvn** [mozilla/mozmaker-templates#33]
A couple options:
- Don't use images in templates
- Base 64 encode images and add to CSS
- Put images on CDN

**Comment by gvn** [comment]
Thoughts @vazquez ?

**Comment by vazquez** [comment]
I think images on CDN would be my preference :)

**Comment by gvn** [comment]
So, actually, I think images in templates is ok, but we should put any partial images on a CDN.
