### ISSUE TITLE
Finalize design for "Two-column, embedded video stream and etherpad" layout

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozmaker-templates#5]
We've started this layout, but during the March 11 heartbeat, we need to finalize. This should include:
- [x] design for specific use case (Curriculum Workshop landing page) (p1)
- [x] generic design (p2)
- [x] design review and necessary revisions

**Comment by hannahkane** [comment]
@vazquez @flukeout - can one of you assign this to yourself?

**Comment by flukeout** [comment]
Progress on this is here - https://github.com/mozilla/mofo-cms-experiment/issues/17 - waiting on @chadsansing for updated copy.

**Comment by chadsansing** [comment]
Copy shared to @flukeout w/ invitation to provide feedback shipped to @amirad, @ldecoursy, @kgorr, and @poh.

**Comment by KGorr** [comment]
Looks great to me, @chadsansing!

**Comment by hannahkane** [comment]
Not sure where to leave this comment, but just wanted to clarify that I think we should have generic version of each layout (with a generic name, such as "3-column CTA" as opposed to "Curriculum Workshop"). For each layout, we should _also_ be able to point to an example from a real use case.

Specifically wondering if the [templates demo](http://mozilla.github.io/mozmaker-templates/demo/) should be updated to reflect the above. Does this make sense, @vazquez @flukeout @gvn?

**Comment by vazquez** [comment]
@hannahkane – You're right, I will update the nav bar on the templates demo to reflect the embedded video stream and etherpad instead of "Curriculum workshop"

**Comment by vazquez** [comment]
We have the template up on the `mozmaker-templates` repo, and it has undergone 2 design reviews. This is good to close, any additional work to be filed as separate tickets.
